// IANA 时区 -> 常见国家代码 的粗略映射。
// 仅覆盖常见时区，用于「时区与 IP 国家是否一致」的启发式判断，
// 无法覆盖到的时区会返回 null，页面会提示「无法判断」而不是误报。
export const TIMEZONE_COUNTRY_MAP: Record<string, string[]> = {
  'Asia/Shanghai': ['CN'],
  'Asia/Chongqing': ['CN'],
  'Asia/Urumqi': ['CN'],
  'Asia/Taipei': ['TW'],
  'Asia/Hong_Kong': ['HK'],
  'Asia/Macau': ['MO'],
  'Asia/Tokyo': ['JP'],
  'Asia/Seoul': ['KR'],
  'Asia/Singapore': ['SG'],
  'Asia/Kuala_Lumpur': ['MY'],
  'Asia/Bangkok': ['TH'],
  'Asia/Jakarta': ['ID'],
  'Asia/Manila': ['PH'],
  'Asia/Ho_Chi_Minh': ['VN'],
  'Asia/Kolkata': ['IN'],
  'Asia/Calcutta': ['IN'],
  'Asia/Dubai': ['AE'],
  'Asia/Karachi': ['PK'],
  'Asia/Dhaka': ['BD'],
  'Asia/Tel_Aviv': ['IL'],
  'Asia/Jerusalem': ['IL'],
  'Asia/Istanbul': ['TR'],
  'Europe/London': ['GB'],
  'Europe/Dublin': ['IE'],
  'Europe/Paris': ['FR'],
  'Europe/Berlin': ['DE'],
  'Europe/Madrid': ['ES'],
  'Europe/Rome': ['IT'],
  'Europe/Amsterdam': ['NL'],
  'Europe/Brussels': ['BE'],
  'Europe/Zurich': ['CH'],
  'Europe/Vienna': ['AT'],
  'Europe/Stockholm': ['SE'],
  'Europe/Oslo': ['NO'],
  'Europe/Copenhagen': ['DK'],
  'Europe/Helsinki': ['FI'],
  'Europe/Warsaw': ['PL'],
  'Europe/Prague': ['CZ'],
  'Europe/Moscow': ['RU'],
  'Europe/Athens': ['GR'],
  'Europe/Lisbon': ['PT'],
  'America/New_York': ['US'],
  'America/Chicago': ['US'],
  'America/Denver': ['US'],
  'America/Los_Angeles': ['US'],
  'America/Anchorage': ['US'],
  'America/Toronto': ['CA'],
  'America/Vancouver': ['CA'],
  'America/Mexico_City': ['MX'],
  'America/Sao_Paulo': ['BR'],
  'America/Argentina/Buenos_Aires': ['AR'],
  'America/Bogota': ['CO'],
  'America/Santiago': ['CL'],
  'Australia/Sydney': ['AU'],
  'Australia/Melbourne': ['AU'],
  'Australia/Brisbane': ['AU'],
  'Australia/Perth': ['AU'],
  'Pacific/Auckland': ['NZ'],
  'Africa/Johannesburg': ['ZA'],
  'Africa/Cairo': ['EG'],
  'Africa/Lagos': ['NG']
}

export function timezoneImpliesCountry(timezone: string): string[] | null {
  return TIMEZONE_COUNTRY_MAP[timezone] ?? null
}
